services:
  frontend_dev:
    container_name: nexus_frontend_dev
    image: docker.io/${DOCKER_USERNAME?error}/${PROJECT_NAME?error}:dev
    restart: always
    ports:
      - '3001:3000'
    env_file:
      - .env
    networks:
      - nexus_frontend_dev_network

  nginx:
    image: nginx:alpine
    container_name: nexus_frontend_nginx_dev
    ports:
      - '9084:80'
    volumes:
      - ./nginx/dev.nexus.conf:/etc/nginx/conf.d/dev.nexus.conf
    depends_on:
      - frontend_dev
    networks:
      - nexus_frontend_dev_network

networks:
  nexus_frontend_dev_network:
    driver: bridge
