export const countries = [
  { id: 1, name: 'Afghanistan' },
  { id: 2, name: 'Åland Islands' },
  { id: 3, name: 'Albania' },
  { id: 4, name: 'Algeria' },
  { id: 5, name: 'American Samoa' },
  { id: 6, name: 'Andorra' },
  { id: 7, name: 'Angola' },
  { id: 8, name: 'Anguilla' },
  { id: 9, name: 'Antarctica' },
  { id: 10, name: 'Antigua and Barbuda' },
  { id: 11, name: 'Argentina' },
  { id: 12, name: 'Armenia' },
  { id: 13, name: 'Aruba' },
  { id: 14, name: 'Australia' },
  { id: 15, name: 'Austria' },
  { id: 16, name: 'Azerbaijan' },
  { id: 17, name: 'Bahamas' },
  { id: 18, name: 'Bahrain' },
  { id: 19, name: 'Bangladesh' },
  { id: 20, name: 'Barbados' },
  { id: 21, name: 'Belarus' },
  { id: 22, name: 'Belgium' },
  { id: 23, name: 'Belize' },
  { id: 24, name: 'Benin' },
  { id: 25, name: 'Bermuda' },
  { id: 26, name: 'Bhutan' },
  { id: 27, name: 'Bolivia' },
  { id: 28, name: 'Bonaire, Sint Eustatius and Saba' },
  { id: 29, name: 'Bosnia and Herzegovina' },
  { id: 30, name: 'Botswana' },
  { id: 31, name: 'Bouvet Island' },
  { id: 32, name: 'Brazil' },
  { id: 33, name: 'British Indian Ocean Territory' },
  { id: 34, name: 'Brunei Darussalam' },
  { id: 35, name: 'Bulgaria' },
  { id: 36, name: 'Burkina Faso' },
  { id: 37, name: 'Burundi' },
  { id: 38, name: 'Cambodia' },
  { id: 39, name: 'Cameroon' },
  { id: 40, name: 'Canada' },
  { id: 41, name: 'Cape Verde' },
  { id: 42, name: 'Cayman Islands' },
  { id: 43, name: 'Central African Republic' },
  { id: 44, name: 'Chad' },
  { id: 45, name: 'Chile' },
  { id: 46, name: 'China' },
  { id: 47, name: 'Christmas Island' },
  { id: 48, name: 'Cocos (Keeling) Islands' },
  { id: 49, name: 'Colombia' },
  { id: 50, name: 'Comoros' },
  { id: 51, name: 'Congo, Republic of the (Brazzaville)' },
  { id: 52, name: 'Congo, the Democratic Republic of the (Kinshasa)' },
  { id: 53, name: 'Cook Islands' },
  { id: 54, name: 'Costa Rica' },
  { id: 55, name: "Côte d'Ivoire, Republic of" },
  { id: 56, name: 'Croatia' },
  { id: 57, name: 'Cuba' },
  { id: 58, name: 'Curaçao' },
  { id: 59, name: 'Cyprus' },
  { id: 60, name: 'Czech Republic' },
  { id: 61, name: 'Denmark' },
  { id: 62, name: 'Djibouti' },
  { id: 63, name: 'Dominica' },
  { id: 64, name: 'Dominican Republic' },
  { id: 65, name: 'Ecuador' },
  { id: 66, name: 'Egypt' },
  { id: 67, name: 'El Salvador' },
  { id: 68, name: 'Equatorial Guinea' },
  { id: 69, name: 'Eritrea' },
  { id: 70, name: 'Estonia' },
  { id: 71, name: 'Ethiopia' },
  { id: 72, name: 'Falkland Islands (Islas Malvinas)' },
  { id: 73, name: 'Faroe Islands' },
  { id: 74, name: 'Fiji' },
  { id: 75, name: 'Finland' },
  { id: 76, name: 'France' },
  { id: 77, name: 'French Guiana' },
  { id: 78, name: 'French Polynesia' },
  { id: 79, name: 'French Southern and Antarctic Lands' },
  { id: 80, name: 'Gabon' },
  { id: 81, name: 'Gambia, The' },
  { id: 82, name: 'Georgia' },
  { id: 83, name: 'Germany' },
  { id: 84, name: 'Ghana' },
  { id: 85, name: 'Gibraltar' },
  { id: 86, name: 'Greece' },
  { id: 87, name: 'Greenland' },
  { id: 88, name: 'Grenada' },
  { id: 89, name: 'Guadeloupe' },
  { id: 90, name: 'Guam' },
  { id: 91, name: 'Guatemala' },
  { id: 92, name: 'Guernsey' },
  { id: 93, name: 'Guinea' },
  { id: 94, name: 'Guinea-Bissau' },
  { id: 95, name: 'Guyana' },
  { id: 96, name: 'Haiti' },
  { id: 97, name: 'Heard Island and McDonald Islands' },
  { id: 98, name: 'Holy See (Vatican City)' },
  { id: 99, name: 'Honduras' },
  { id: 100, name: 'Hong Kong' },
  { id: 101, name: 'Hungary' },
  { id: 102, name: 'Iceland' },
  { id: 103, name: 'India' },
  { id: 104, name: 'Indonesia' },
  { id: 105, name: 'Iran, Islamic Republic of' },
  { id: 106, name: 'Iraq' },
  { id: 107, name: 'Ireland' },
  { id: 108, name: 'Isle of Man' },
  { id: 109, name: 'Israel' },
  { id: 110, name: 'Italy' },
  { id: 111, name: 'Jamaica' },
  { id: 112, name: 'Japan' },
  { id: 113, name: 'Jersey' },
  { id: 114, name: 'Jordan' },
  { id: 115, name: 'Kazakhstan' },
  { id: 116, name: 'Kyrgyzstan' },
  { id: 117, name: 'Kenya' },
  { id: 118, name: 'Kiribati' },
  { id: 119, name: "Korea, Democratic People's Republic of" },
  { id: 120, name: 'Korea, Republic of' },
  { id: 121, name: 'Kosovo' },
  { id: 122, name: 'Kuwait' },
  { id: 123, name: 'Laos' },
  { id: 124, name: 'Latvia' },
  { id: 125, name: 'Lebanon' },
  { id: 126, name: 'Lesotho' },
  { id: 127, name: 'Liberia' },
  { id: 128, name: 'Libya' },
  { id: 129, name: 'Liechtenstein' },
  { id: 130, name: 'Lithuania' },
  { id: 131, name: 'Luxembourg' },
  { id: 132, name: 'Macao' },
  { id: 133, name: 'Macedonia, Republic of' },
  { id: 134, name: 'Madagascar' },
  { id: 135, name: 'Malawi' },
  { id: 136, name: 'Malaysia' },
  { id: 137, name: 'Maldives' },
  { id: 138, name: 'Mali' },
  { id: 139, name: 'Malta' },
  { id: 140, name: 'Marshall Islands' },
  { id: 141, name: 'Martinique' },
  { id: 142, name: 'Mauritania' },
  { id: 143, name: 'Mauritius' },
  { id: 144, name: 'Mayotte' },
  { id: 145, name: 'Mexico' },
  { id: 146, name: 'Micronesia, Federated States of' },
  { id: 147, name: 'Moldova' },
  { id: 148, name: 'Monaco' },
  { id: 149, name: 'Mongolia' },
  { id: 150, name: 'Montenegro' },
  { id: 151, name: 'Montserrat' },
  { id: 152, name: 'Morocco' },
  { id: 153, name: 'Mozambique' },
  { id: 154, name: 'Myanmar' },
  { id: 155, name: 'Namibia' },
  { id: 156, name: 'Nauru' },
  { id: 157, name: 'Nepal' },
  { id: 158, name: 'Netherlands' },
  { id: 159, name: 'New Caledonia' },
  { id: 160, name: 'New Zealand' },
  { id: 161, name: 'Nicaragua' },
  { id: 162, name: 'Niger' },
  { id: 163, name: 'Nigeria' },
  { id: 164, name: 'Niue' },
  { id: 165, name: 'Norfolk Island' },
  { id: 166, name: 'Northern Mariana Islands' },
  { id: 167, name: 'Norway' },
  { id: 168, name: 'Oman' },
  { id: 169, name: 'Pakistan' },
  { id: 170, name: 'Palau' },
  { id: 171, name: 'Palestine, State of' },
  { id: 172, name: 'Panama' },
  { id: 173, name: 'Papua New Guinea' },
  { id: 174, name: 'Paraguay' },
  { id: 175, name: 'Peru' },
  { id: 176, name: 'Philippines' },
  { id: 177, name: 'Pitcairn' },
  { id: 178, name: 'Poland' },
  { id: 179, name: 'Portugal' },
  { id: 180, name: 'Puerto Rico' },
  { id: 181, name: 'Qatar' },
  { id: 182, name: 'Réunion' },
  { id: 183, name: 'Romania' },
  { id: 184, name: 'Russian Federation' },
  { id: 185, name: 'Rwanda' },
  { id: 186, name: 'Saint Barthélemy' },
  { id: 187, name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { id: 188, name: 'Saint Kitts and Nevis' },
  { id: 189, name: 'Saint Lucia' },
  { id: 190, name: 'Saint Martin' },
  { id: 191, name: 'Saint Pierre and Miquelon' },
  { id: 192, name: 'Saint Vincent and the Grenadines' },
  { id: 193, name: 'Samoa' },
  { id: 194, name: 'San Marino' },
  { id: 195, name: 'Sao Tome and Principe' },
  { id: 196, name: 'Saudi Arabia' },
  { id: 197, name: 'Senegal' },
  { id: 198, name: 'Serbia' },
  { id: 199, name: 'Seychelles' },
  { id: 200, name: 'Sierra Leone' },
  { id: 201, name: 'Singapore' },
  { id: 202, name: 'Sint Maarten (Dutch part)' },
  { id: 203, name: 'Slovakia' },
  { id: 204, name: 'Slovenia' },
  { id: 205, name: 'Solomon Islands' },
  { id: 206, name: 'Somalia' },
  { id: 207, name: 'South Africa' },
  { id: 208, name: 'South Georgia and South Sandwich Islands' },
  { id: 209, name: 'South Sudan' },
  { id: 210, name: 'Spain' },
  { id: 211, name: 'Sri Lanka' },
  { id: 212, name: 'Sudan' },
  { id: 213, name: 'Suriname' },
  { id: 214, name: 'Swaziland' },
  { id: 215, name: 'Sweden' },
  { id: 216, name: 'Switzerland' },
  { id: 217, name: 'Syrian Arab Republic' },
  { id: 218, name: 'Taiwan' },
  { id: 219, name: 'Tajikistan' },
  { id: 220, name: 'Tanzania, United Republic of' },
  { id: 221, name: 'Thailand' },
  { id: 222, name: 'Timor-Leste' },
  { id: 223, name: 'Togo' },
  { id: 224, name: 'Tokelau' },
  { id: 225, name: 'Tonga' },
  { id: 226, name: 'Trinidad and Tobago' },
  { id: 227, name: 'Tunisia' },
  { id: 228, name: 'Turkey' },
  { id: 229, name: 'Turkmenistan' },
  { id: 230, name: 'Turks and Caicos Islands' },
  { id: 231, name: 'Tuvalu' },
  { id: 232, name: 'Uganda' },
  { id: 233, name: 'Ukraine' },
  { id: 234, name: 'United Arab Emirates' },
  { id: 235, name: 'United Kingdom' },
  { id: 236, name: 'United States' },
  { id: 237, name: 'United States Minor Outlying Islands' },
  { id: 238, name: 'Uruguay' },
  { id: 239, name: 'Uzbekistan' },
  { id: 240, name: 'Vanuatu' },
  { id: 241, name: 'Venezuela, Bolivarian Republic of' },
  { id: 242, name: 'Vietnam' },
  { id: 243, name: 'Virgin Islands, British' },
  { id: 244, name: 'Virgin Islands, U.S.' },
  { id: 245, name: 'Wallis and Futuna' },
  { id: 246, name: 'Western Sahara' },
  { id: 247, name: 'Yemen' },
  { id: 248, name: 'Zambia' },
  { id: 249, name: 'Zimbabwe' },
];
