
export const fakeData = [
  {
    id: 'A1@3B$',
    name: 'John Doe',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    phone: '+998 (90) 123 45 67',
    paymentStatus: false,
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: false,
    visaStatus: false,
    status: {
      statusOne: 'disabled',
      statusTwo: 'disabled',
      statusThree: 'disabled',
      statusFour: 'disabled',
      statusFive: 'disabled',
    },
  },
  {
    id: 'C2#4D%',
    name: 'Jane Smith',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (91) 234 56 78',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: true,
    applicationStatus: true,
    paymentStatus: false,
    visaStatus: false,
    status: {
      statusOne: 'done',
      statusTwo: 'done',
      statusThree: 'current',
      statusFour: 'reject',
      statusFive: 'disabled',
    },
  },
  {
    id: 'E3^5F&',
    name: 'Michael Johnson',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    phone: '+998 (92) 345 67 89',
    dealer: 'Muzaffar F.',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: false,
    documentDate: '22.12.2024',
    paymentStatus: true,
    visaStatus: true,
    status: {
      statusOne: 'disabled',
      statusTwo: 'current',
      statusThree: 'done',
      statusFour: 'reject',
      statusFive: 'done',
    },
  },
  {
    id: 'G4*6H(',
    name: 'Emily Davis',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (93) 456 78 90',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: true,
    applicationStatus: true,
    visaStatus: 'pending',
    paymentStatus: false,
    status: {
      statusOne: 'reject',
      statusTwo: 'done',
      statusThree: 'disabled',
      statusFour: 'current',
      statusFive: 'done',
    },
  },
  {
    id: 'I5@7J)',
    name: 'William Brown',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    phone: '+998 (94) 567 89 01',
    translationsGivenDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: false,
    translationsExpectedDate: '22.12.2024',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: false,
    visaStatus: true,
    status: {
      statusOne: 'done',
      statusTwo: 'reject',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'K6#8L!',
    name: 'Olivia Wilson',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (95) 678 90 12',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    dealer: 'Muzaffar F.',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    documentDate: '22.12.2024',
    paymentStatus: true,
    visaStatus: 'pending',
    status: {
      statusOne: 'current',
      statusTwo: 'disabled',
      statusThree: 'done',
      statusFour: 'reject',
      statusFive: 'done',
    },
  },
  {
    id: 'M7^9N$',
    name: 'James Taylor',
    sprintId: 'B23-F-000001',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: false,
    certificat: 'TOPIK B1',
    phone: '+998 (96) 789 01 23',
    dealer: 'Muzaffar F.',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    documentDate: '22.12.2024',
    paymentStatus: false,
    visaStatus: true,
    status: {
      statusOne: 'done',
      statusTwo: 'reject',
      statusThree: 'disabled',
      statusFour: 'current',
      statusFive: 'done',
    },
  },
  {
    id: 'O8*0P%',
    name: 'Sophia Martinez',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (97) 890 12 34',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: true,
    applicationStatus: false,
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: true,
    visaStatus: false,
    status: {
      statusOne: 'reject',
      statusTwo: 'done',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'Q9@1R^',
    name: 'Alexander Anderson',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    phone: '+998 (98) 901 23 45',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: false,
    visaStatus: false,
    status: {
      statusOne: 'done',
      statusTwo: 'disabled',
      statusThree: 'current',
      statusFour: 'reject',
      statusFive: 'done',
    },
  },
  {
    id: 'S1#2T&',
    name: 'Mia Thomas',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (99) 012 34 56',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    paymentStatus: true,
    visaStatus: false,
    status: {
      statusOne: 'reject',
      statusTwo: 'done',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'U2^3V*',
    name: 'David Jackson',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    translationsGivenDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: false,
    translationsExpectedDate: '22.12.2024',
    phone: '+998 (90) 123 45 67',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: false,
    visaStatus: false,
    status: {
      statusOne: 'done',
      statusTwo: 'reject',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'W3@4X(',
    name: 'Charlotte White',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    phone: '+998 (91) 234 56 78',
    dealer: 'Muzaffar F.',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    documentDate: '22.12.2024',
    paymentStatus: true,
    visaStatus: false,
    status: {
      statusOne: 'current',
      statusTwo: 'done',
      statusThree: 'reject',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'Y4#5Z)',
    name: 'Daniel Harris',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    phone: '+998 (92) 345 67 89',
    date: '22.12.2024',
    applicationFee: false,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: false,
    visaStatus: false,
    status: {
      statusOne: 'disabled',
      statusTwo: 'current',
      statusThree: 'done',
      statusFour: 'reject',
      statusFive: 'done',
    },
  },
  {
    id: 'A5^6B!',
    name: 'Amelia Martin',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: false,
    universityName: 'ACC - Gyeonggi',
    interview: true,
    applicationStatus: false,
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (93) 456 78 90',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: true,
    visaStatus: false,
    status: {
      statusOne: 'reject',
      statusTwo: 'done',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'C6@7D$',
    name: 'Matthew Thompson',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    phone: '+998 (94) 567 89 01',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: true,
    date: '22.12.2024',
    applicationFee: false,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    visaStatus: false,
    status: {
      statusOne: 'done',
      statusTwo: 'reject',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'E7#8F%',
    name: 'Harper Garcia',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (95) 678 90 12',
    translationsGivenDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: false,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    translationsExpectedDate: '22.12.2024',
    dealer: 'Muzaffar F.',
    visaStatus: false,
    paymentStatus: true,
    documentDate: '22.12.2024',
    status: {
      statusOne: 'current',
      statusTwo: 'done',
      statusThree: 'reject',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'G8^9H&',
    name: 'Joseph Lewis',
    sprintId: 'B23-F-000001',
    certificat: 'TOPIK B1',
    phone: '+998 (96) 789 01 23',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: false,
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    dealer: 'Muzaffar F.',
    paymentStatus: false,
    visaStatus: false,
    documentDate: '22.12.2024',
    status: {
      statusOne: 'done',
      statusTwo: 'reject',
      statusThree: 'disabled',
      statusFour: 'current',
      statusFive: 'done',
    },
  },
  {
    id: 'I9*0J(',
    name: 'Evelyn Lee',
    sprintId: 'B23-F-000002',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: true,
    applicationStatus: true,
    certificat: 'IELTS 8.5',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    phone: '+998 (97) 890 12 34',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    visaStatus: false,
    paymentStatus: false,
    status: {
      statusOne: 'reject',
      statusTwo: 'done',
      statusThree: 'current',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'K0@1L)',
    name: 'Samuel Walker',
    sprintId: 'B23-F-000001',
    translationsGivenDate: '22.12.2024',
    translationsExpectedDate: '22.12.2024',
    certificat: 'TOPIK B1',
    phone: '+998 (98) 901 23 45',
    dealer: 'Muzaffar F.',
    date: '22.12.2024',
    applicationFee: true,
    universityName: 'ACC - Gyeonggi',
    interview: false,
    applicationStatus: true,
    documentDate: '22.12.2024',
    paymentStatus: true,
    visaStatus: false,
    status: {
      statusOne: 'done',
      statusTwo: 'current',
      statusThree: 'reject',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
  {
    id: 'M1#2N!',
    name: 'Abigail Robinson',
    sprintId: 'B23-F-000002',
    certificat: 'IELTS 8.5',
    phone: '+998 (99) 012 34 56',
    translationsGivenDate: '22.12.2024',
    date: '22.12.2024',
    applicationFee: true,
    visaStatus: false,
    universityName: 'ACC - Gyeonggi',
    interview: true,
    applicationStatus: true,
    translationsExpectedDate: '22.12.2024',
    dealer: 'Muzaffar F.',
    documentDate: '22.12.2024',
    paymentStatus: true,
    status: {
      statusOne: 'current',
      statusTwo: 'done',
      statusThree: 'reject',
      statusFour: 'disabled',
      statusFive: 'done',
    },
  },
];
